spring.application.name=RateLimiter
spring.data.redis.host=free-labrador-66076.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAQIcAAIncDEyOGVjYTRlYzY5MjY0Njg1OTFjZGI5MjllNWY1MTk2ZnAxNjYwNzY
spring.data.redis.ssl.enabled=true